name: Unit Testing

on:
  pull_request:
    branches:
      - test

jobs:
  unit-testing:
    name: Run Unit Tests
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add steps to install dependencies and run unit tests
